{% set name = "thepipe" %}
{% set version = "1.3.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/thepipe-{{ version }}.tar.gz
  sha256: c3c6c9db093a4de1387794d948326c03767e52262539616360f8a1dd68289257

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools_scm
  run:
    - numpy
    - pip >=9
    - psutil
    - python >=3.5
    - python-dateutil
    - pytz
    - setuptools_scm
    - toml

test:
  imports:
    - thepipe
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/tamasgal/thepipe
  summary: A lightweight, general purpose pipeline framework.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tamasgal
